### ISSUE TITLE
Retranslations/duplicated chapters by multiple translation groups (Issue)

### ISSUE THREAD

**Issue by cloudiirain** [WeebWare/Ranobe-Honyaku-API#10]
## User Story

Once upon a time, **Translator Bob** starts translating **_My Sister Little Can't Program_**. He translates about nine chapters (~1.5 volumes) before he goes MIA and disappears forever.

**Translator Joe** decides he's going to start translating **_My Little Sister Can't Program_**. He takes one look at Bob's translation and goes: "Ick, this is terrible! I'm going to retranslate this!" Joe manages to retranslate about five chapters before he goes MIA and disappears forever.
### The question: What should we do when Translator Joe shows up?
- Delete Translator Bob's translations and replace it with Joe's?
- Tell Joe he can't post his retranslations because Bob got there first?
- Keep both Bob and Joe's translations? But how will that work for a linear app where chapters are ordered in a list, and generally speaking readers should be able to click "Next Chapter"?
## What should we do?

I brought this up not because I had a good solution, but because it's a case I've seen many times in the past (whether on Baka-Tsuki or on the web). I'm not saying we need to implement a solution for it -- can we can choose not to address it -- but I think it's helpful to keep unusual cases in our minds as we're designing models, and know that they are there.

**Comment by viggy96** [comment]
I think maybe we should have an is active timer of sorts to determine if a project is active (which can also be set manually). Then, if the project is no longer active, someone else can pick up.

Then, when the new translations come in, replace the old ones. (but keep the old ones somehow in version control.

**Comment by Fuyukai** [comment]
Do not delete old translations.

The third option is looking like the best, but **Do not delete old translations.**

**Comment by scraeling** [comment]
Allow multiple versions of the same chapters. Chapters and volumes will be attributed to the respective translator or group, and users will be able to pick the version they prefer when they click on a link from the series page.

**Comment by cloudiirain** [comment]
@scraeling works well when navigating from an index, but what about when we need to provide a next/previous chapter links at the bottom of chapters, etc?

**Comment by scraeling** [comment]
Go to the next chapter in the context of that volume. Similarly, next volume by group/translator.

The models need to be changed to support these relationships.
- Chapters will be grouped under Volumes
- Chapters may be grouped under a Series(for WN)
- Volumes will be grouped under the creator/owner(User) of that volume
- Volumes will be grouped under Series

For example:
- Series X has a field referencing Volumes A, B, C...
- Volumes A and B may have the same volume_number, but are from different(unique) creators
- Volume A contains 1,2,3... Chapters

I hope that makes sense.

**Comment by cloudiirain** [comment]
Ah wait, I liked this, but there's another situation where two translation groups are working together to translate a series and not duplicating chapters. For instance, [there was a period in Tensei Slime (WN) project when two translation groups were basically alternating chapters](http://www.novelupdates.com/series/tensei-shitara-slime-datta-ken/?pg=7).

```
Date    Group   Release
08/28/15    Circus Translations c97
08/26/15    Circus Translations c96
08/24/15    Guro Translation    c95
08/23/15    Circus Translations c94
08/21/15    Circus Translations c93
08/20/15    Guro Translation    c92
08/19/15    Circus Translations c91
08/19/15    Guro Translation    c90
08/18/15    Circus Translations c89
08/16/15    Circus Translations c88
```

**Comment by scraeling** [comment]
If the next volume/chapter exists, but isn't from the same source, ask the reader if they want to continue?

**Comment by danieltanfh95** [comment]
I think allowing multiple versions of the current chapter is confusing to the reader. I think keeping the most recent version as the accessible version to the reader keep but all versions available to the current translator, since they are now in charge of the project. If bob wants to object, stop being MIA and submit his objection to the current translator.

**Comment by byronvanstien** [comment]
Old translations will be overwritten, this is what versions are for, if translator Bob comes back and doesn't like the fact his translations were overwritten he can talk to the current translator (if any) about it, we shouldn't have to babysit the translators. As for translation groups, I believe it'd be better to have their releases separated slightly as it'd be considered an `owned` project (kind of like private, but only available to group members, with reading as public)
